- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Start nginx service
  service:
    name: nginx
    state: started
    enabled: true

- name: Copy Harden Configuration
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-available/{{ domain }}.conf
    owner: root
    group: root
    mode: '0644'

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
